import type { GearDBItem } from '@/types/gear';

export const GEAR_DATABASE: GearDBItem[] = [
  // ─── TOPs ───────────────────────────────────────────
  {
    id: 'rcf912',
    nombre: 'RCF ART 912-A',
    marca: 'RCF',
    categoria: 'tops',
    specs: 'Activo · 700W · 131dB · 12"',
    emoji: '🔴',
    activo: true,
    potenciaW: 700,
    maxSpl: 131,
  },
  {
    id: 'rcf910',
    nombre: 'RCF ART 910-A',
    marca: 'RCF',
    categoria: 'tops',
    specs: 'Activo · 400W · 128dB · 10"',
    emoji: '🔴',
    activo: true,
    potenciaW: 400,
    maxSpl: 128,
  },
  {
    id: 'qsck12',
    nombre: 'QSC K12.2',
    marca: 'QSC',
    categoria: 'tops',
    specs: 'Activo · 2000W · 131dB · 12"',
    emoji: '🔵',
    activo: true,
    potenciaW: 2000,
    maxSpl: 131,
  },
  {
    id: 'jbl715',
    nombre: 'JBL EON715',
    marca: 'JBL',
    categoria: 'tops',
    specs: 'Activo · 1300W · 129dB · 15"',
    emoji: '🟡',
    activo: true,
    potenciaW: 1300,
    maxSpl: 129,
  },
  {
    id: 'yam12',
    nombre: 'Yamaha DXR12',
    marca: 'Yamaha',
    categoria: 'tops',
    specs: 'Activo · 1100W · 131dB · 12"',
    emoji: '⚫',
    activo: true,
    potenciaW: 1100,
    maxSpl: 131,
  },
  {
    id: 'pv215',
    nombre: 'Peavy PV215',
    marca: 'Peavy',
    categoria: 'tops',
    specs: 'Pasivo · 350W · 124dB · 2×15"',
    emoji: '⬜',
    activo: false,
    potenciaW: 350,
    maxSpl: 124,
  },

  // ─── SUBs ───────────────────────────────────────────
  {
    id: 'air18',
    nombre: 'PreSonus AIR18',
    marca: 'PreSonus',
    categoria: 'subs',
    specs: 'Activo · 1000W · 133dB · 18"',
    emoji: '🟠',
    activo: true,
    potenciaW: 1000,
    maxSpl: 133,
  },
  {
    id: 'rcf905',
    nombre: 'RCF ART 905-AS',
    marca: 'RCF',
    categoria: 'subs',
    specs: 'Activo · 700W · 133dB · 15"',
    emoji: '🔴',
    activo: true,
    potenciaW: 700,
    maxSpl: 133,
  },
  {
    id: 'jbl718',
    nombre: 'JBL EON718S',
    marca: 'JBL',
    categoria: 'subs',
    specs: 'Activo · 1300W · 135dB · 18"',
    emoji: '🟡',
    activo: true,
    potenciaW: 1300,
    maxSpl: 135,
  },

  // ─── Amplificadores ─────────────────────────────────
  {
    id: 'geminip800',
    nombre: 'Gemini P-800',
    marca: 'Gemini',
    categoria: 'amps',
    specs: '250W×2 @ 8Ω — Backup',
    emoji: '⚡',
    activo: false,
    potenciaW: 250,
    maxSpl: 0,
  },
  {
    id: 'crown',
    nombre: 'Crown XLS 1002',
    marca: 'Crown',
    categoria: 'amps',
    specs: '350W×2 @ 8Ω',
    emoji: '⚡',
    activo: false,
    potenciaW: 350,
    maxSpl: 0,
  },

  // ─── DSP ────────────────────────────────────────────
  {
    id: 'dcx2496',
    nombre: 'Behringer DCX2496',
    marca: 'Behringer',
    categoria: 'dsp',
    specs: '6 salidas · 24bit/96kHz · LR24',
    emoji: '⚙️',
    activo: false,
    potenciaW: 0,
    maxSpl: 0,
  },
  {
    id: 'driverack',
    nombre: 'dbx DriveRack PA2',
    marca: 'dbx',
    categoria: 'dsp',
    specs: '2×6 salidas · Auto-EQ · RTA',
    emoji: '⚙️',
    activo: false,
    potenciaW: 0,
    maxSpl: 0,
  },

  // ─── Mixers ──────────────────────────────────────────
  {
    id: 'sl2442',
    nombre: 'Behringer SL2442FX',
    marca: 'Behringer',
    categoria: 'mixer',
    specs: '24 canales · 4 Aux · FX',
    emoji: '🎚️',
    activo: false,
    potenciaW: 0,
    maxSpl: 0,
  },
  {
    id: 'm32',
    nombre: 'Midas M32',
    marca: 'Midas',
    categoria: 'mixer',
    specs: '32 canales · digital',
    emoji: '🎚️',
    activo: false,
    potenciaW: 0,
    maxSpl: 0,
  },

  // ─── Mics ────────────────────────────────────────────
  {
    id: 'sm58',
    nombre: 'Shure SM58',
    marca: 'Shure',
    categoria: 'mics',
    specs: 'Dinámico cardioide · voz',
    emoji: '🎤',
    activo: false,
    potenciaW: 0,
    maxSpl: 0,
  },
  {
    id: 'sm48',
    nombre: 'Shure SM48',
    marca: 'Shure',
    categoria: 'mics',
    specs: 'Dinámico cardioide · predicador',
    emoji: '🎤',
    activo: false,
    potenciaW: 0,
    maxSpl: 0,
  },
  {
    id: 'beta58',
    nombre: 'Shure Beta 58A',
    marca: 'Shure',
    categoria: 'mics',
    specs: 'Dinámico supercardioide · líder',
    emoji: '🎤',
    activo: false,
    potenciaW: 0,
    maxSpl: 0,
  },
  {
    id: 'atcond',
    nombre: 'AT Condensador',
    marca: 'AudioTechnica',
    categoria: 'mics',
    specs: 'Condensador cardioide · 48V',
    emoji: '🎤',
    activo: false,
    potenciaW: 0,
    maxSpl: 0,
  },
]

export function getGearByCategory(cat: string) {
  return GEAR_DATABASE.filter((g) => g.categoria === cat)
}

export function getGearById(id: string) {
  return GEAR_DATABASE.find((g) => g.id === id)
}
